name: embrace_dio_example
description: Demonstrates how to use the embrace_dio package with the embrace plugin.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ">=4.0.0 <6.0.0"
  embrace: ^2.0.0
  embrace_dio:
    # When depending on this package from a real application you should use:
    #   embrace_dio: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true