name: embrace_platform_interface
description: A common platform interface for the Embrace plugin that enables platform-specific implementations.
version: 4.2.0
homepage: https://embrace.io
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  flutter:
    sdk: flutter
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=3.0.2 <5.0.0"
