name: embrace_dio

on:
  pull_request:
    paths:
      - ".github/workflows/embrace_dio.yaml"
      - "embrace_dio/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/embrace_dio.yaml"
      - "embrace_dio/**"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/flutter_ci.yaml
    with:
      flutter_channel: stable
      flutter_version: "3.22.0"
      working_directory: embrace_dio
