# Adapted from VGV's defaults: https://github.com/VeryGoodOpenSource/very_good_workflows

name: Flutter Package Workflow

on:
  workflow_call:
    inputs:
      concurrency:
        required: false
        type: number
        default: 4
      coverage_excludes:
        required: false
        type: string
        default: ""
      flutter_channel:
        required: false
        type: string
        default: "stable"
      flutter_version:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
      min_coverage:
        required: false
        type: number
        default: 0 # increase this in future.
      test_optimization:
        required: false
        type: boolean
        default: true
      test_recursion:
        required: false
        type: boolean
        default: false
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good packages get --recursive

      - name: ✨ Check Formatting
        run: flutter format --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: flutter analyze lib test

      - name: 🧪 Run Tests
        run: very_good test -j ${{ inputs.concurrency }} ${{ (inputs.test_recursion && '--recursive') || '' }} ${{ (inputs.test_optimization && '--optimization') || '--no-optimization' }} --coverage --test-randomize-ordering-seed random

      - name: 📊 Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@c953fca3e24a915e111cc6f55f03f756dcb3964c # v3.0.0
        with:
          path: ${{ inputs.working_directory }}/coverage/lcov.info
          exclude: ${{ inputs.coverage_excludes }}
          min_coverage: ${{ inputs.min_coverage }}
