# Invokes the release workflow whenever a release candidate PR is merged
name: RC Release

permissions:
  contents: write

on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    if: contains(github.event.pull_request.labels.*.name, 'release-candidate') && github.event.pull_request.merged == true
    name: Publish Release
    uses: ./.github/workflows/release.yaml
    with:
      dry-run: false
    secrets: inherit
