name: Release

env:
  REPO_PATH: 'embrace-flutter-sdk'

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Validate but do not push the package'
        type: boolean
        required: true
  workflow_call:
    inputs:
      dry-run:
        description: 'Validate but do not push the package'
        type: boolean
        required: true

permissions:
  contents: read

jobs:
  verify-versions:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: ${{ env.REPO_PATH }}
          persist-credentials: false

      - name: Setup yq
        run: |
          sudo snap install yq

      - name: Verify Package Versions
        run: |
          cd ${{ env.REPO_PATH }}
          ./verify_versions.sh

      - name: Validate access to version data service
        uses: embrace-io/public-actions/upload-sdk-version@88167cd1a3fce3418e26c8c842026e6dfab99e41
        with:
          platform: 'flutter'
          version: '0.0.0'  # We are just validating the token here, so the version is not important
          dryRun: true
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}

  publish-packages:
    name: Publish Packages
    needs: verify-versions
    uses: ./.github/workflows/publish_flutter_packages.yaml
    with:
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit

  create-release:
    name: Create Release
    needs: publish-packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: ${{ env.REPO_PATH }}
          persist-credentials: true

      - name: Setup yq
        run: |
          sudo snap install yq

      - name: Parse Version
        run: |
          cd ${{ env.REPO_PATH }}
          export PACKAGE_VERSION=$(yq -r .version embrace/pubspec.yaml)
          echo "${PACKAGE_VERSION}"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Tag commit
        run: |
          cd ${{ env.REPO_PATH }}
          git config --global user.name "embrace-ci"
          git config --global user.email "embrace-ci@users.noreply.github.com"
          git tag -a ${PACKAGE_VERSION} -m "${PACKAGE_VERSION}"
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Push Tag
        if: ${{ inputs.dry-run == false }}
        run: |
          cd ${{ env.REPO_PATH }}
          git push --tags

      - name: Create Release
        if: ${{ inputs.dry-run == false }}
        run: |
          cd ${{ env.REPO_PATH }}
          gh release create ${PACKAGE_VERSION} -t ${PACKAGE_VERSION} -F embrace/CHANGELOG.md
        env:
          GH_TOKEN: ${{ github.token }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Record SDK Version History
        uses: embrace-io/public-actions/upload-sdk-version@88167cd1a3fce3418e26c8c842026e6dfab99e41
        if: ${{ inputs.dry-run == false }}
        with:
          platform: 'flutter'
          version: ${{ env.PACKAGE_VERSION }}
          dryRun: false
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
